### ISSUE TITLE
wrong page/tab title for the module from Learn

### ISSUE THREAD

**Issue by SJeannie** [learn-co-curriculum/array-methods-lab#10]
Second issue:
When I tried to create my previous issue (of the test not accepting array.reverse! as a solution) from Learn (ask a question --> create issue), it said that I'm in the Speaking Grandma lab (wrong page/tab title for the module, too).

The correct title would be "array-methods-lab".  That looks obvious on this page, but I had to search for this within the curriculum repository to get here ^-^;

**Comment by morgvanny** [comment]
Ah, seems like a bug in learn.co possibly. Closing this issue, as it doesn't pertain to this particular repository.
